[package]
name = "smelt"
version = "0.0.0-replace-me"
edition = "2024"

[dependencies]
tokio = "1"
zip = "4"
terminal = { path = "../terminal" }
pastey = "0.1.0"
cursive = "0.21.1"
indicatif = "0.17.11"
inquire = "0.7.5"
