[package]
name = "hashmap"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
lrtexec_lib = { version = "0.0.0-replace-me", path = "../../types", features = [
  "sudo",
], default-features = false }
