[package]
name = "lrtexec_lib"
version = "0.0.0-replace-me"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
libc = "0.2.174"
lrt_macros = { path = "../macros" }
pastey = "0.1.0"

[features]
default = ["v_all"]
memory = []

# LRTEXEC Interpreter Versions
v_all = ["v0"]
v0 = []


