[package]
name = "lrtexec_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
stabby = "72.1.1"
lrt_macros = { path = "../macros" }

[features]
default = ["v_all"]
memory = []

# LRTEXEC Interpreter Versions
v_all = ["v0"]
v0 = []
