[package]
name = "async_waker"
version = "0.0.0-replace-me"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
lrtexec_lib = { version = "0.0.0-replace-me", path = "../types", default-features = false }
