name: Build LRT

on:
  push:

permissions: write-all

jobs:
  getver:
    name: Get version

    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.release_data.outputs.result }}
      id: ${{ steps.release.outputs.id }}
      upload_url: ${{ steps.release.outputs.upload_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        shell: pwsh
        run: ./version.ps1

      - name: Get Version
        id: release_data
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { readFileSync } = require("fs");

            const version = readFileSync("./.version").toString();

            return version;

      - name: Get Tag
        id: tag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { readFileSync } = require("fs");

            const tag = readFileSync("./.tag").toString();

            return tag;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          tag_name: ${{ steps.tag.outputs.result }}
          name: LRT ${{ steps.tag.outputs.result }}
          generate_release_notes: true
          body_path: ./RELEASE.md
          append_body: true
          files: |
            ./.build
          draft: true

  build-gui:
    name: Build with GUI (Dialog)

    needs: [getver]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # windows-latest + -pc-windows-msvc
          - os: windows-latest
            arch: x86_64
            suffix: "-pc-windows-msvc"
          - os: windows-latest
            arch: aarch64
            suffix: "-pc-windows-msvc"
          - os: windows-latest
            arch: i686
            suffix: "-pc-windows-msvc"

          # windows-latest + -win7-windows-msvc
          - os: windows-latest
            arch: x86_64
            suffix: "-win7-windows-msvc"
          - os: windows-latest
            arch: i686
            suffix: "-win7-windows-msvc"

          # macos-latest
          - os: macos-latest
            arch: x86_64
            suffix: "-apple-darwin"

          - os: macos-latest
            arch: aarch64
            suffix: "-apple-darwin"

          # ubuntu-22.04 (x86_64)
          - os: ubuntu-22.04
            arch: x86_64
            suffix: "-unknown-linux-gnu"

          # ubuntu-22.04-arm (aarch64)
          - os: ubuntu-22.04-arm
            arch: aarch64
            suffix: "-unknown-linux-gnu"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Build target
        id: target
        shell: pwsh
        run: |
          echo "target=${{ matrix.arch }}${{ matrix.suffix }}" >> $env:GITHUB_OUTPUT

      - name: Prerequisites
        shell: pwsh
        run: |
          rustup default nightly
          rustup toolchain install nightly

          rustup target add --toolchain nightly ${{ steps.target.outputs.target }}

          "${{ needs.getver.outputs.version }}" > .version

      - name: Run build script
        shell: pwsh
        env:
          RELEASE: "true"
          BUILD_TARGET: ${{ steps.target.outputs.target }}
        run: |
          ./build.ps1

  build-nogui:
    name: Build without GUI

    needs: [getver]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: x86_64
            suffix: "-unknown-linux-gnu"

          - os: ubuntu-22.04
            arch: i686
            suffix: "-unknown-linux-gnu"

          - os: ubuntu-22.04-arm
            arch: aarch64
            suffix: "-unknown-linux-gnu"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load new version
        shell: pwsh
        run: |
          "${{ needs.getver.outputs.version }}" > .version

  handle:
    name: Handle artifacts
    needs: [getver, build-gui, build-nogui]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Release if failure
        if: needs.build-gui.result != 'success' || needs.build-nogui.result != 'success'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.getver.outputs.id }}
            });

      - name: Undraft release if success
        if: needs.build-gui.result == 'success' && needs.build-nogui.result == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ needs.getver.outputs.id }},
              draft: false
            });
